/*
* generated by Xtext
*/
package com.temenos.interaction.rimdsl;

import org.eclipse.xtext.generator.IGenerator;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.temenos.interaction.rimdsl.generator.RIMDslGeneratorSwagger;

/*******************************************************************************
 * Copyright © Temenos Headquarters SA 1993-2019.  All rights reserved.
 *******************************************************************************/

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class RIMDslStandaloneSetupSwagger extends RIMDslStandaloneSetup {

	public static void doSetup() {
		new RIMDslStandaloneSetupSwagger().createInjectorAndDoEMFRegistration();
	}
	
	public Injector createInjector() {
		return Guice.createInjector(new com.temenos.interaction.rimdsl.RIMDslRuntimeModule() {
			
			@Override
			public Class<? extends IGenerator> bindIGenerator() {
				return RIMDslGeneratorSwagger.class;
			}
			
		});
	}
	
}

