/*
 * generated by Xtext
 */
package com.temenos.interaction.rimdsl;

import org.eclipse.xtext.generator.IGenerator;

import com.temenos.interaction.rimdsl.generator.RIMDslGeneratorSwagger;

/*******************************************************************************
 * Copyright © Temenos Headquarters SA 1993-2019.  All rights reserved.
 *******************************************************************************/

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RIMDslRuntimeModuleSwagger extends RIMDslRuntimeModule {

	public Class<? extends IGenerator> bindIGenerator() {
		return RIMDslGeneratorSwagger.class;
	}

	@Override
	public Class<? extends org.eclipse.xtext.resource.containers.IAllContainersState.Provider> bindIAllContainersState$Provider() {
		return FasterResourceSetBasedAllContainersStateProvider.class;
	}
}
